### ISSUE TITLE
Repeated options

### ISSUE THREAD

**Issue by luc-j-bourhis** [davetron5000/optparse-plus#118]
I would like `foo --bar first --bar second --bar third` to result in `options[:bar] == %w(first second third)`. Methadone doesn't support that out of the box, does it?

**Comment by davetron5000** [comment]
I don’t belive it does.  Ultimately, methadone uses Ruby’s `OptionParser`, so to get an array, you’d do:

```ruby
on(“bar”,Array)
```

And to invoke it:

```ruby
> foo --bar=first,second,third
```
