### ISSUE TITLE
Scroll lags heavily on the website

### ISSUE THREAD

**Issue by staring-frog** [davetron5000/optparse-plus#120]
There's some problem with http://davetron5000.github.io/methadone/
It's only there do I get so heavy lagging when wheel-scrolling. Very heavy lagging.

PS Thanks for a great gem.

**Comment by davetron5000** [comment]
What browser/OS?  It seems OK to me but I only have access to a macbook pro.

**Comment by nicktime** [comment]
It's Ubuntu 16.04, Chrome. Still lags with all extensions disabled. But in Guest mode it's alright. Firefox is fine too. No idea why's that. Never ran into this before.

**Comment by davetron5000** [comment]
Can't repro this, plus it's been a few years.

**Comment by staring-frog** [comment]
Yep, probably was a problem on my side, sorry :man_shrugging:
