### ISSUE TITLE
Methadone does not create a "/features" directory in my system 

### ISSUE THREAD

**Issue by psomdeb25** [davetron5000/optparse-plus#122]
System OS: macOS
Version: 10.13.6

I have installed the latest version of rvm (rvm 1.29.4 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]), ruby (ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin17]). 

Created a separate gem list called testing and installed methadone in it. When I type in “methadone --readme --license=apache fullstop” it creates the "fullstop" directory but there is something not quite right. I do not have the "/features" directory in my "fullstop" folder. Without the features directory in the fullstop I cannot work out a lot of examples in the book. In the book, using the methadone command creates "fullstop" containing the directory called "features".

Book Title: Kick the Bash habit with Ruby and methadone

(imgur link attached here: https://i.imgur.com/BhTdkgu.png)

How do you think I can correct it?

Thank you!!

**Comment by davetron5000** [comment]
Hey, sorry the book is now a bit out of date.   had to move away from using Cucumber and Aruba as those tools have changed in incompatible ways.

You can now write your integration tests in Test::Unit.  You can use [`BaseIntegrationTest`](https://github.com/davetron5000/methadone/blob/master/lib/methadone/test/base_integration_test.rb) as your base class and [`IntegrationTestAssertions`](https://github.com/davetron5000/methadone/blob/master/lib/methadone/test/integration_test_assertions.rb) to assert things about how your app behaves.

Unfortunately, updating the iBook is fairly difficult so it may have to languish :(
